rpc:
  name: yurpc
  version: 2.0
  serverPort: 8082
  mock: false
  serializer: jdk
  loadBalancer: consistentHash
  retryStrategy: no
  registryConfig:
    registry: etcd
    address: localhost:2379