rpc:
  name: yurpc
  version: 2.0
  serverPort: 8081
  mock: false
  serializer: jdk
  loadBalancer: random
  retryStrategy: fixedInterval
  tolerantStrategy: failSafe
  registryConfig:
    registry: etcd
    address: localhost:2379