rpc:
  name: yurpc
  version: 2.0
  serverPort: 8081
  mock: false
  serializer: jdk
  loadBalancer: roundRobin
  retryStrategy: no1
  tolerantStrategy: failSafe
  registryConfig:
    registry: etcd
    address: localhost:2379